name: madeit
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_dotenv: ^5.0.2
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^4.0.0
  kakao_flutter_sdk: ^1.1.1
  crypto: ^3.0.2
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  firebase_dynamic_links: ^4.2.5
  # share_plus: ^4.0.7
  url_launcher: ^6.1.3
  # flutter_email_sender: ^5.1.0
  rxdart: ^0.27.4
  antenna: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
